from pyramid.config import Configurator
from pyramid.response import Response

def main(global_config, **settings):
    config = Configurator(settings=settings)
    config.include('gandi_pyramid_prometheus')
    config.include('pyramid_chameleon')
    config.add_route('home', '/')
    config.add_route('forward', '/forward')
    config.add_route('backward', '/backward')
    config.add_route('left', '/left')
    config.add_route('right', '/right')
    config.add_route('stop', '/stop')
    config.add_route('north', '/north')
    config.add_route('south', '/south')
    config.add_route('west', '/west')
    config.add_route('east', '/east')
    config.add_route('stoptwo', '/stoptwo')
    config.add_route('servomin', '/servomin')
    config.add_route('servomid', '/servomid')
    config.add_route('servomax', '/servomax')
    config.add_route('servomin2', '/servomin2')
    config.add_route('servomid2', '/servomid2')
    config.add_route('servomax2', '/servomax2')
    config.add_route('thirty', '/thirty')
    config.add_route('fifty', '/fifty')
    config.add_route('full', '/full')
    config.add_route('linuson', '/linuson')
    config.add_route('linusoff', '/linusoff')
    config.add_route('torvaldson', '/torvaldson')
    config.add_route('torvaldsoff', '/torvaldsoff')
    config.scan('.views')
    config.add_static_view(name='static', path='dual:static')
    return config.make_wsgi_app()