apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: pyramidport
  labels:
    name: pyramid-dual
    release: prometheus
  name: pyramid-dual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyramid-dual
  template:
    metadata:
      labels:
        app: pyramid-dual
    spec:
      containers:
      - env:
        - name: JAEGER_HOST
          value : my-jaeger-tracing-default-agent.default.svc.cluster.local
        name: pyramid-dual
        image: linuxrobotgeek/pyramid-dual:latest
        imagePullPolicy: Always
        ports:
        - name: pyramidport
          containerPort: 6543
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pyramid-dual
  labels:
    app: pyramid-dual
spec:
  selector:
    app: pyramid-dual
  ports:
    - name: pyramid-dual
      protocol: TCP
      port: 6543
      targetPort: pyramidport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pyramid-dual
  namespace: monitoring
  labels:
    app: pyramid-dual
    release: prometheus
spec:
  selector:
    matchLabels:
      app: pyramid-dual
  endpoints:
  - port: pyramid-dual
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
